import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { getEmployeeDashboard, getManagementSummary, getManagementNotifications } from '../api/dashboard';
import { getDepartments } from '../api/departments';
import { useAuth } from '../context/AuthContext';
import Navbar from '../components/Navbar';
import StatCard from '../components/StatCard';
import StatusBadge from '../components/StatusBadge';
import { jsPDF } from 'jspdf';
import { 
  AlertTriangle, 
  Clock, 
  TrendingUp, 
  CheckCircle,
  Plus,
  Eye,
  FileText,
  Activity,
  Users,
  Building,
  Calendar,
  RefreshCw,
  Download,
  Printer,
  User,
  ArrowUp,
  ArrowDown,
  Minus,
  CheckSquare,
  Search
} from 'lucide-react';

const Dashboard = () => {
  const { user, isHOD, isSafetyOfficer, isAdmin, isGeneralManager, isPlantHead, isSeniorManagement, isManagementUser } = useAuth();
  const navigate = useNavigate();

  // Common State
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // 1. Employee / HOD Dashboard State
  const [stats, setStats] = useState(null);

  // 2. Management Dashboard State
  const [kpis, setKpis] = useState([]);
  const [notifications, setNotifications] = useState(null);
  const [departments, setDepartments] = useState([]);
  const [filters, setFilters] = useState({
    start_date: '',
    end_date: '',
    department_id: '',
    status: '',
    severity: '',
    incident_category: '',
    location: '',
    user_type: ''
  });

  useEffect(() => {
    if (isManagementUser) {
      fetchManagementData();
      fetchDepartments();
    } else {
      fetchEmployeeDashboardData();
    }
  }, [isManagementUser]);

  // Fetch standard dashboard data (Employee / HOD / Safety Officer)
  const fetchEmployeeDashboardData = async () => {
    setLoading(true);
    try {
      const response = await getEmployeeDashboard();
      setStats(response.data);
    } catch (err) {
      console.error("Error fetching dashboard statistics", err);
      setError('Could not load safety dashboard metrics.');
    } finally {
      setLoading(false);
    }
  };

  // Fetch departments for filter dropdown
  const fetchDepartments = async () => {
    try {
      const response = await getDepartments();
      setDepartments(response.data);
    } catch (err) {
      console.error("Error fetching departments", err);
    }
  };

  // Fetch management dashboard data with current filters
  const fetchManagementData = async (activeFilters = filters) => {
    setLoading(true);
    setError('');
    try {
      const params = {};
      Object.keys(activeFilters).forEach(key => {
        if (activeFilters[key]) params[key] = activeFilters[key];
      });

      const [summaryRes, notifRes] = await Promise.all([
        getManagementSummary(params),
        getManagementNotifications(params)
      ]);

      setKpis(summaryRes.data);
      setNotifications(notifRes.data);
    } catch (err) {
      console.error("Error fetching management statistics", err);
      setError('Failed to fetch plant safety summary metrics.');
    } finally {
      setLoading(false);
    }
  };

  const handleFilterChange = (e) => {
    const { name, value } = e.target;
    const newFilters = { ...filters, [name]: value };
    setFilters(newFilters);
    fetchManagementData(newFilters);
  };

  const handleResetFilters = () => {
    const defaultFilters = {
      start_date: '',
      end_date: '',
      department_id: '',
      status: '',
      severity: '',
      incident_category: '',
      location: '',
      user_type: ''
    };
    setFilters(defaultFilters);
    fetchManagementData(defaultFilters);
  };

  // Client-side PDF generation using jsPDF
  const handleExportPDF = () => {
    if (!kpis.length) return;
    
    const doc = new jsPDF();
    
    // Header styling
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(21, 101, 192); // Vizag Blue
    doc.text("RASHTRIYA ISPAT NIGAM LIMITED (RINL)", 14, 20);
    
    doc.setFontSize(14);
    doc.setTextColor(46, 125, 50); // Vizag Green
    doc.text("VIZAG STEEL PLANT - SAFETY MANAGEMENT PORTAL", 14, 28);
    
    doc.setFontSize(11);
    doc.setTextColor(110, 110, 110);
    doc.text(`Safety Dashboard Executive Summary Report`, 14, 34);
    doc.text(`Generated By: ${user?.name || 'Management User'} (${user?.role})`, 14, 40);
    doc.text(`Date & Time: ${new Date().toLocaleString()}`, 14, 45);
    doc.line(14, 49, 196, 49);

    // Render active filters in PDF
    doc.setFontSize(9);
    doc.setFont("Helvetica", "bold");
    doc.text("Active Report Filters:", 14, 56);
    doc.setFont("Helvetica", "normal");
    
    const activeFiltersList = [];
    if (filters.start_date) activeFiltersList.push(`Start Date: ${filters.start_date}`);
    if (filters.end_date) activeFiltersList.push(`End Date: ${filters.end_date}`);
    if (filters.department_id) {
      const deptName = departments.find(d => String(d.department_id) === String(filters.department_id))?.department_name;
      activeFiltersList.push(`Department: ${deptName || filters.department_id}`);
    }
    if (filters.status) activeFiltersList.push(`Status: ${filters.status}`);
    if (filters.severity) activeFiltersList.push(`Severity: ${filters.severity}`);
    if (filters.incident_category) activeFiltersList.push(`Category: ${filters.incident_category}`);
    if (filters.location) activeFiltersList.push(`Location: ${filters.location}`);
    if (filters.user_type) activeFiltersList.push(`Reporter Role: ${filters.user_type}`);
    
    const filterText = activeFiltersList.length > 0 ? activeFiltersList.join(" | ") : "None (All Plant)";
    doc.text(filterText, 48, 56, { maxWidth: 145 });

    doc.line(14, 60, 196, 60);

    // Render KPIs as a table structure
    let y = 70;
    doc.setFontSize(12);
    doc.setFont("Helvetica", "bold");
    doc.setTextColor(21, 101, 192);
    doc.text("Safety Key Performance Indicators (KPIs)", 14, y);
    
    y += 8;
    // Draw table headers
    doc.setFillColor(21, 101, 192);
    doc.rect(14, y, 182, 8, "F");
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text("Safety Indicator Metric", 16, y + 6);
    doc.text("Value", 110, y + 6);
    doc.text("Monthly Change (%)", 145, y + 6);
    
    doc.setFont("Helvetica", "normal");
    doc.setTextColor(33, 33, 33);
    
    y += 8;
    kpis.forEach((kpi) => {
      // Draw grid line
      doc.setDrawColor(220, 220, 220);
      doc.line(14, y + 7, 196, y + 7);
      
      doc.text(kpi.title, 16, y + 5);
      doc.setFont("Helvetica", "bold");
      doc.text(String(kpi.value), 110, y + 5);
      doc.setFont("Helvetica", "normal");
      
      const changeText = kpi.change !== undefined ? `${kpi.change > 0 ? '+' : ''}${kpi.change}% (${kpi.trend})` : 'N/A';
      doc.text(changeText, 145, y + 5);
      
      y += 8;
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
    });

    // Save generated document
    doc.save(`vizag_steel_safety_dashboard_${new Date().toISOString().slice(0, 10)}.pdf`);
  };

  const handlePrint = () => {
    window.print();
  };

  const getKPIIcon = (iconName) => {
    switch (iconName) {
      case "AlertTriangle": return <AlertTriangle size={20} />;
      case "Clock": return <Clock size={20} />;
      case "Activity": return <Activity size={20} />;
      case "Eye": return <Eye size={20} />;
      case "CheckSquare": return <CheckSquare size={20} />;
      case "CheckCircle": return <CheckCircle size={20} />;
      case "Building": return <Building size={20} />;
      case "Users": return <Users size={20} />;
      case "User": return <User size={20} />;
      case "Calendar": return <Calendar size={20} />;
      default: return <FileText size={20} />;
    }
  };

  const getKPITrendIcon = (trend) => {
    if (trend === "up") return <ArrowUp size={14} style={{ color: 'inherit' }} />;
    if (trend === "down") return <ArrowDown size={14} style={{ color: 'inherit' }} />;
    return <Minus size={14} style={{ color: 'inherit' }} />;
  };

  const getDashboardWelcome = () => {
    if (isAdmin) return "Steel Plant Safety Operations Control (Admin Panel)";
    if (isSafetyOfficer) return "Plant Safety Command & Investigation Dashboard";
    if (isHOD) return `${user?.department} - Department Safety & Approvals`;
    if (isGeneralManager) return "General Manager - Executive Plant Overview";
    if (isPlantHead) return "Plant Head - Corporate Safety & Incident Command";
    if (isSeniorManagement) return "Senior Management Board - Plant-wide Safety Read-Only Portal";
    return "Personal Incident Reporting & Safety Portal";
  };

  if (loading && !kpis.length && !stats) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ textAlign: 'center' }}>
          <RefreshCw className="animate-spin" size={32} color="var(--primary-blue)" style={{ margin: '0 auto 1rem' }} />
          <p style={{ color: 'var(--primary-blue)', fontWeight: '700' }}>Loading RINL Safety Systems...</p>
        </div>
      </div>
    );
  }

  // --- RENDER BRANCH 1: MANAGEMENT EXECUTIVE DASHBOARD ---
  if (isManagementUser) {
    return (
      <div style={{ display: 'flex', width: '100%' }}>
        <div className="main-content" style={{ width: '100%' }}>
          <Navbar title="Management Executive Dashboard" />
          
          <div className="page-body fade-in" style={{ padding: '1.5rem' }}>
            
            {/* Welcome banner & Actions Toolbar */}
            <div className="glass-card no-print" style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: '2rem',
              padding: '1.5rem 2rem',
              backgroundColor: 'var(--light-blue)',
              borderLeft: '4px solid var(--primary-blue)',
              border: '1px solid var(--border-color)',
              borderLeftWidth: '4px',
              borderRadius: '4px'
            }}>
              <div>
                <h1 style={{ fontSize: '1.4rem', fontWeight: '700', color: 'var(--primary-blue)', marginBottom: '0.2rem' }}>
                  Welcome, Director/Executive {user?.name}
                </h1>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.825rem', fontWeight: '600' }}>
                  {getDashboardWelcome()}
                </p>
              </div>
              
              <div style={{ display: 'flex', gap: '0.75rem' }}>
                <button onClick={handleExportPDF} className="btn" style={{ backgroundColor: 'var(--primary-blue)', color: '#FFF', display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.85rem', fontWeight: 'bold' }}>
                  <Download size={15} />
                  <span>PDF Summary</span>
                </button>
                <button onClick={handlePrint} className="btn" style={{ backgroundColor: 'var(--success-green)', color: '#FFF', display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.85rem', fontWeight: 'bold' }}>
                  <Printer size={15} />
                  <span>Print Dashboard</span>
                </button>
                <button onClick={() => fetchManagementData()} className="btn btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.85rem' }}>
                  <RefreshCw size={15} />
                  <span>Refresh</span>
                </button>
              </div>
            </div>

            {/* Filter Toolbar Panel */}
            <div className="glass-card no-print" style={{ padding: '1.5rem', backgroundColor: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '4px', marginBottom: '2rem' }}>
              <h3 style={{ fontSize: '0.95rem', color: 'var(--primary-blue)', borderBottom: '2px solid var(--light-blue)', paddingBottom: '0.4rem', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 'bold' }}>
                <Search size={16} />
                <span>Executive Query & Analytics Filters</span>
              </h3>
              
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', fontSize: '0.8rem' }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>Start Date</label>
                  <input type="date" name="start_date" className="form-input" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.start_date} onChange={handleFilterChange} />
                </div>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>End Date</label>
                  <input type="date" name="end_date" className="form-input" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.end_date} onChange={handleFilterChange} />
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>Department Scope</label>
                  <select name="department_id" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.department_id} onChange={handleFilterChange}>
                    <option value="">-- All Departments --</option>
                    {departments.map(d => <option key={d.department_id} value={d.department_id}>{d.department_name}</option>)}
                  </select>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>Incident Status</label>
                  <select name="status" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.status} onChange={handleFilterChange}>
                    <option value="">-- All Statuses --</option>
                    <option value="Pending">Pending Review</option>
                    <option value="Under Investigation">Under Investigation</option>
                    <option value="Corrective Action Assigned">Corrective Action Assigned</option>
                    <option value="Implementation In Progress">Implementation In Progress</option>
                    <option value="Implementation Completed">Implementation Completed</option>
                    <option value="Closed">Closed</option>
                  </select>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>Severity Level</label>
                  <select name="severity" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.severity} onChange={handleFilterChange}>
                    <option value="">-- All Severities --</option>
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                    <option value="Critical">Critical</option>
                  </select>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>Incident Category</label>
                  <select name="incident_category" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.incident_category} onChange={handleFilterChange}>
                    <option value="">-- All Categories --</option>
                    <option value="Unsafe Act">Unsafe Act</option>
                    <option value="Unsafe Condition">Unsafe Condition</option>
                    <option value="Both">Both</option>
                  </select>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>Location</label>
                  <input type="text" name="location" placeholder="e.g. Blast Furnace" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.location} onChange={handleFilterChange} />
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <label style={{ fontWeight: '700' }}>Reporter Role</label>
                  <select name="user_type" style={{ padding: '0.4rem', border: '1px solid var(--border-color)', borderRadius: '4px' }} value={filters.user_type} onChange={handleFilterChange}>
                    <option value="">-- All Roles --</option>
                    <option value="Employee">Employee</option>
                    <option value="Trainee">Trainee</option>
                    <option value="Intern">Intern</option>
                    <option value="Contractor">Contractor</option>
                  </select>
                </div>
              </div>
              
              <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '1.25rem' }}>
                <button type="button" onClick={handleResetFilters} className="btn btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.8rem' }}>
                  <RefreshCw size={14} />
                  <span>Reset Filters</span>
                </button>
              </div>
            </div>

            {error && (
              <div style={{ backgroundColor: '#FFEBEE', border: '1px solid #FFCDD2', color: '#C62828', padding: '1rem', borderRadius: '4px', marginBottom: '2rem', fontWeight: '600' }}>
                {error}
              </div>
            )}

            {/* RINL Letterhead Logo for Print View Only */}
            <div className="print-only" style={{ display: 'none', alignItems: 'center', borderBottom: '3px double var(--primary-blue)', paddingBottom: '10px', marginBottom: '30px' }}>
              <div style={{ flexGrow: 1 }}>
                <h3 style={{ fontSize: '1.5rem', fontWeight: 'bold', color: 'var(--primary-blue)', margin: 0 }}>
                  RASHTRIYA ISPAT NIGAM LIMITED (RINL)
                </h3>
                <span style={{ fontSize: '0.95rem', color: 'var(--success-green)', fontWeight: 'bold' }}>
                  VIZAG STEEL PLANT - SAFETY PORTAL SUMMARY
                </span>
              </div>
            </div>

            {/* KPI Cards Grid */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
              gap: '1.25rem',
              marginBottom: '2.5rem'
            }}>
              {kpis.map((kpi, idx) => {
                const isOverdue = kpi.title === "Overdue Incidents";
                const isNormalInfo = ["Total Departments", "Total Registered Users", "Reporting Employees", "Avg Resolution Time"].includes(kpi.title);
                
                let trendColor = 'var(--text-muted)';
                if (!isNormalInfo) {
                  if (kpi.color === 'danger') trendColor = '#D32F2F';
                  if (kpi.color === 'success') trendColor = '#388E3C';
                  if (kpi.color === 'info') trendColor = 'var(--primary-blue)';
                }
                
                return (
                  <div key={idx} className="glass-card" style={{
                    backgroundColor: '#FFFFFF',
                    border: '1px solid var(--border-color)',
                    borderRadius: '6px',
                    padding: '1.25rem',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'space-between',
                    minHeight: '120px',
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)'
                  }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                      <span style={{ fontSize: '0.75rem', fontWeight: '700', color: 'var(--text-secondary)', textTransform: 'uppercase', tracking: '0.05em' }}>
                        {kpi.title}
                      </span>
                      <div style={{ 
                        padding: '0.4rem', 
                        borderRadius: '4px', 
                        backgroundColor: isOverdue ? '#FFEBEE' : 'var(--light-blue)', 
                        color: isOverdue ? '#D32F2F' : 'var(--primary-blue)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center'
                      }}>
                        {getKPIIcon(kpi.icon)}
                      </div>
                    </div>

                    <div style={{ marginTop: '0.5rem' }}>
                      <span style={{ fontSize: '1.75rem', fontWeight: '800', color: isOverdue && parseInt(kpi.value) > 0 ? '#C62828' : 'var(--text-primary)' }}>
                        {kpi.value}
                      </span>
                    </div>

                    {!isNormalInfo && !isOverdue && (
                      <div style={{ 
                        marginTop: '0.5rem', 
                        display: 'flex', 
                        alignItems: 'center', 
                        gap: '0.25rem', 
                        fontSize: '0.7rem', 
                        fontWeight: '700',
                        color: trendColor 
                      }}>
                        {getKPITrendIcon(kpi.trend)}
                        <span>{kpi.change}% change vs last month</span>
                      </div>
                    )}
                    
                    {isOverdue && (
                      <div style={{ marginTop: '0.5rem', fontSize: '0.7rem', fontWeight: '700', color: parseInt(kpi.value) > 0 ? '#C62828' : 'var(--text-muted)' }}>
                        {parseInt(kpi.value) > 0 ? "Requires immediate HOD attention" : "No overdue corrective actions"}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Alarms and Recent Activity Grid */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(450px, 1fr))',
              gap: '2rem'
            }}>
              
              {/* Safety Alarm and Alerts Panel */}
              <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', backgroundColor: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '4px', padding: '1.5rem' }}>
                <h3 style={{ fontSize: '1.1rem', color: '#C62828', display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 'bold' }}>
                  <AlertTriangle size={20} color="#C62828" />
                  <span>Real-time Safety Alert Center</span>
                </h3>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', maxHeight: '420px', overflowY: 'auto' }}>
                  {notifications?.overdue_actions?.count > 0 && (
                    <div style={{ borderLeft: '4px solid #C62828', backgroundColor: '#FFEBEE', padding: '0.85rem', borderRadius: '4px', fontSize: '0.8rem' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', color: '#C62828', marginBottom: '0.25rem' }}>
                        <span>OVERDUE CORRECTIVE ACTIONS</span>
                        <span>{notifications.overdue_actions.count} Items</span>
                      </div>
                      <p style={{ margin: 0, color: '#333' }}>Safety actions past target resolution deadlines. Requires HOD escalation.</p>
                    </div>
                  )}

                  {notifications?.high_priority_incidents?.count > 0 && (
                    <div style={{ borderLeft: '4px solid #E65100', backgroundColor: '#FFF3E0', padding: '0.85rem', borderRadius: '4px', fontSize: '0.8rem' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', color: '#E65100', marginBottom: '0.25rem' }}>
                        <span>CRITICAL / HIGH SEVERITY ALARMS</span>
                        <span>{notifications.high_priority_incidents.count} Incidents</span>
                      </div>
                      <p style={{ margin: 0, color: '#333' }}>Critical near misses flagged. Review root causes and immediate safety containment.</p>
                      <div style={{ marginTop: '0.5rem', display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                        {notifications.high_priority_incidents.items.slice(0, 3).map(inc => (
                          <div key={inc.id} style={{ display: 'flex', justifyContent: 'space-between', borderTop: '1px solid rgba(0,0,0,0.05)', paddingTop: '0.25rem', fontSize: '0.75rem' }}>
                            <span>{inc.incident_number} - {inc.title}</span>
                            <span style={{ fontWeight: 'bold' }}>{inc.potential_severity}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {notifications?.pending_incidents?.count > 0 && (
                    <div style={{ borderLeft: '4px solid var(--primary-blue)', backgroundColor: 'var(--light-blue)', padding: '0.85rem', borderRadius: '4px', fontSize: '0.8rem' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', color: 'var(--primary-blue)', marginBottom: '0.25rem' }}>
                        <span>PENDING REVIEW ASSIGNMENTS</span>
                        <span>{notifications.pending_incidents.count} Incidents</span>
                      </div>
                      <p style={{ margin: 0, color: '#333' }}>Reports awaiting HOD investigation/CAPA assignment.</p>
                    </div>
                  )}

                  {(!notifications || (notifications.overdue_actions?.count === 0 && notifications.high_priority_incidents?.count === 0 && notifications.pending_incidents?.count === 0)) && (
                    <div style={{ padding: '3rem', textStyle: 'italic', color: 'var(--text-secondary)', textAlign: 'center' }}>
                      No critical safety alarms or pending alerts registered.
                    </div>
                  )}
                </div>
              </div>

              {/* Recent Activity List */}
              <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', backgroundColor: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '4px', padding: '1.5rem' }}>
                <h3 style={{ fontSize: '1.1rem', color: 'var(--primary-blue)', display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 'bold' }}>
                  <Activity size={20} color="var(--primary-blue)" />
                  <span>Recent Safety Operations & Closed Issues</span>
                </h3>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', maxHeight: '420px', overflowY: 'auto' }}>
                  {notifications?.recently_closed_incidents?.count > 0 ? (
                    notifications.recently_closed_incidents.items.map(inc => (
                      <div key={inc.id} style={{ 
                        backgroundColor: '#F9F9F9', 
                        border: '1px solid var(--border-color)', 
                        padding: '0.75rem', 
                        borderRadius: '4px',
                        fontSize: '0.8rem',
                        display: 'flex',
                        flexDirection: 'column',
                        gap: '0.25rem'
                      }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', color: 'var(--success-green)' }}>
                          <span>Incident Closed Successfully</span>
                          <span>{inc.incident_number}</span>
                        </div>
                        <span style={{ fontWeight: '600' }}>{inc.title}</span>
                        <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--text-muted)', fontSize: '0.7rem' }}>
                          <span>Dept: {inc.department_code}</span>
                          <span>Closed: {inc.closed_date ? new Date(inc.closed_date).toLocaleDateString() : 'N/A'}</span>
                        </div>
                      </div>
                    ))
                  ) : (
                    <div style={{ padding: '3rem', color: 'var(--text-secondary)', textAlign: 'center' }}>
                      No incidents closed in the last 10 days.
                    </div>
                  )}
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>
    );
  }

  // --- RENDER BRANCH 2: EMPLOYEE / HOD / SAFETY OFFICER DASHBOARD ---
  return (
    <div style={{ display: 'flex', width: '100%' }}>
      <div className="main-content" style={{ width: '100%' }}>
        <Navbar title="Safety Management Dashboard" />
        
        <div className="page-body fade-in" style={{ padding: '1.5rem' }}>
          {/* Welcome Panel */}
          <div className="glass-card" style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '2rem',
            padding: '2rem',
            backgroundColor: 'var(--light-blue)',
            borderLeft: '4px solid var(--primary-blue)',
            border: '1px solid var(--border-color)',
            borderLeftWidth: '4px',
            borderRadius: '4px'
          }}>
            <div>
              <h1 style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--primary-blue)', marginBottom: '0.25rem' }}>
                Welcome Back, {user?.name}!
              </h1>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem', fontWeight: '600' }}>
                {getDashboardWelcome()}
              </p>
            </div>
            
            {!(isGeneralManager || isPlantHead || isSeniorManagement) && (
              <button 
                className="btn btn-primary"
                onClick={() => navigate('/report')}
              >
                <Plus size={16} />
                <span>Report Near Miss</span>
              </button>
            )}
          </div>

          {error && (
            <div style={{
              backgroundColor: '#FFEBEE',
              border: '1px solid #FFCDD2',
              color: '#C62828',
              padding: '1rem',
              borderRadius: '4px',
              marginBottom: '2rem',
              fontWeight: '600'
            }}>
              {error}
            </div>
          )}

          {/* KPIs Row */}
          {stats && (
            <div className="kpi-grid" style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
              gap: '1.5rem',
              marginBottom: '2rem'
            }}>
              <StatCard 
                title="Total Reports" 
                value={stats.total_count} 
                icon={FileText} 
                color="#1976D2" 
              />
              <StatCard 
                title="Pending Investigation" 
                value={stats.pending_count + stats.investigating_count} 
                icon={Clock} 
                color="#E65100" 
              />
              <StatCard 
                title="Actions Active" 
                value={stats.action_count} 
                icon={TrendingUp} 
                color="#4A148C" 
              />
              <StatCard 
                title="Resolved & Closed" 
                value={stats.resolved_count + stats.closed_count} 
                icon={CheckCircle} 
                color="#1B5E20" 
              />
            </div>
          )}

          <div style={{
            display: 'grid',
            gridTemplateColumns: isAdmin ? '1.5fr 1fr' : '1fr',
            gap: '2rem'
          }}>
            {/* Recent Incidents Table Card */}
            <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', backgroundColor: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '4px', padding: '1.5rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <h3 style={{ fontSize: '1.1rem', color: 'var(--primary-blue)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <AlertTriangle size={18} color="var(--primary-blue)" />
                  <span>Recent Near Miss Incident Reports</span>
                </h3>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: '600' }}>
                  Showing last 5 reports
                </span>
              </div>

              <div className="table-container">
                <table className="custom-table" style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                  <thead>
                    <tr style={{ borderBottom: '2px solid var(--border-color)', textAlign: 'left' }}>
                      <th style={{ padding: '0.75rem' }}>Title</th>
                      <th style={{ padding: '0.75rem' }}>Department</th>
                      <th style={{ padding: '0.75rem' }}>Location</th>
                      <th style={{ padding: '0.75rem' }}>Severity</th>
                      <th style={{ padding: '0.75rem' }}>Status</th>
                      <th style={{ padding: '0.75rem' }}>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {stats?.recent_incidents?.length > 0 ? (
                      stats.recent_incidents.map((incident) => (
                        <tr key={incident.id} style={{ borderBottom: '1px solid var(--border-color)' }}>
                          <td style={{ fontWeight: '600', padding: '0.75rem' }}>
                            <div style={{ display: 'flex', flexDirection: 'column' }}>
                              <span style={{ color: 'var(--text-primary)' }}>{incident.title}</span>
                              <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{incident.incident_number}</span>
                            </div>
                          </td>
                          <td style={{ padding: '0.75rem' }}>{incident.department_code}</td>
                          <td style={{ padding: '0.75rem' }}>{incident.location}</td>
                          <td style={{ padding: '0.75rem' }}>
                            <StatusBadge type="severity" value={incident.potential_severity} />
                          </td>
                          <td style={{ padding: '0.75rem' }}>
                            <StatusBadge type="status" value={incident.status} />
                          </td>
                          <td style={{ padding: '0.75rem' }}>
                            <Link 
                              to={`/incidents/${incident.id}`}
                              className="btn btn-secondary"
                              style={{ padding: '0.4rem 0.75rem', fontSize: '0.75rem' }}
                            >
                              <Eye size={12} />
                              <span>View</span>
                            </Link>
                          </td>
                        </tr>
                      ))
                    ) : (
                      <tr>
                        <td colSpan="6" style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '2rem' }}>
                          No incidents reported recently.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Admin Audit Logs Panel */}
            {isAdmin && stats?.audit_logs && (
              <div className="glass-card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', backgroundColor: '#FFFFFF', border: '1px solid var(--border-color)', borderRadius: '4px', padding: '1.5rem' }}>
                <h3 style={{ fontSize: '1.1rem', color: 'var(--primary-blue)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Activity size={18} color="var(--safety-orange)" />
                  <span>System Activity Audit Logs</span>
                </h3>
                
                <div style={{
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '0.85rem',
                  maxHeight: '360px',
                  overflowY: 'auto',
                  paddingRight: '0.5rem'
                }}>
                  {stats.audit_logs.length > 0 ? (
                    stats.audit_logs.map((log) => (
                      <div 
                        key={log.id} 
                        style={{
                          backgroundColor: 'var(--bg-light-gray)',
                          border: '1px solid var(--border-color)',
                          borderRadius: '4px',
                          padding: '0.75rem',
                          fontSize: '0.75rem',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '0.25rem'
                        }}
                      >
                        <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--primary-blue)' }}>
                          <span style={{ fontWeight: '700' }}>{log.action}</span>
                          <span style={{ color: 'var(--text-muted)' }}>{new Date(log.created_at).toLocaleTimeString()}</span>
                        </div>
                        <div style={{ color: 'var(--text-primary)', fontWeight: '500' }}>{log.details}</div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--text-muted)', fontSize: '0.675rem', marginTop: '0.15rem' }}>
                          <span>User: {log.username}</span>
                          <span>IP: {log.ip_address}</span>
                        </div>
                      </div>
                    ))
                  ) : (
                    <div style={{ textAlign: 'center', color: 'var(--text-muted)', padding: '2rem' }}>
                      No audit logs captured.
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
};

export default Dashboard;
