-- Supabase/PostgreSQL schema for the existing Flask application.
-- Run this in Supabase SQL Editor before using the app against Supabase.

create table if not exists departments (
  department_id bigint generated by default as identity primary key,
  department_name varchar(100) unique not null,
  department_code varchar(10) unique not null,
  status varchar(20) not null default 'Active',
  created_at timestamptz not null default now()
);

create table if not exists users (
  user_id bigint generated by default as identity primary key,
  employee_id varchar(30) unique not null,
  name varchar(100) not null,
  email varchar(100) unique not null,
  password varchar(255) not null,
  role varchar(50) not null,
  mobile_number varchar(20),
  department_id bigint references departments(department_id) on delete set null,
  status varchar(20) not null default 'Active',
  first_login boolean not null default true,
  temporary_password boolean not null default true,
  password_reset_required boolean not null default true,
  created_by bigint references users(user_id) on delete set null,
  password_changed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists incidents (
  incident_id bigint generated by default as identity primary key,
  incident_number varchar(50) unique not null,
  title varchar(150) not null,
  description text not null,
  reported_by bigint not null references users(user_id) on delete cascade,
  department_id bigint not null references departments(department_id) on delete cascade,
  location varchar(150) not null,
  equipment_involved varchar(100),
  incident_type varchar(50) not null,
  potential_severity varchar(20) not null default 'Low',
  status varchar(50) not null default 'Pending',
  reported_date timestamptz not null default now(),
  photograph_path varchar(255),
  probable_cause text,
  root_cause text,
  immediate_action text,
  preventive_action text,
  severity varchar(20),
  priority varchar(20),
  investigation_remarks text,
  verification_remarks text,
  closed_by bigint references users(user_id) on delete set null,
  closed_date timestamptz
);

create table if not exists incident_reviews (
  review_id bigint generated by default as identity primary key,
  incident_id bigint not null references incidents(incident_id) on delete cascade,
  reviewed_by bigint not null references users(user_id) on delete cascade,
  comments text not null,
  review_status varchar(50) not null,
  review_date timestamptz not null default now()
);

create table if not exists corrective_actions (
  action_id bigint generated by default as identity primary key,
  incident_id bigint not null references incidents(incident_id) on delete cascade,
  root_cause text not null,
  corrective_action text not null,
  responsible_person bigint references users(user_id) on delete set null,
  closure_date timestamptz,
  assigned_department bigint references departments(department_id) on delete set null,
  target_completion_date timestamptz,
  action_status varchar(50) not null default 'Not Started',
  completion_date timestamptz,
  implementation_remarks text,
  action_type varchar(50) not null default 'Corrective',
  status varchar(50) not null default 'Pending',
  closure_remarks text
);

create table if not exists registration_requests (
  request_id bigint generated by default as identity primary key,
  employee_id varchar(30) not null,
  full_name varchar(100) not null,
  email varchar(100) not null,
  mobile_number varchar(20) not null,
  department_id bigint not null references departments(department_id) on delete cascade,
  user_type varchar(30) not null,
  password_hash varchar(255) not null,
  request_status varchar(20) not null default 'Pending',
  hod_remarks text,
  created_at timestamptz not null default now(),
  hod_id bigint references users(user_id) on delete set null
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references users(user_id) on delete set null,
  action varchar(255) not null,
  details text,
  ip_address varchar(45),
  created_at timestamptz not null default now()
);

create index if not exists idx_users_employee_id on users(employee_id);
create index if not exists idx_users_department_id on users(department_id);
create index if not exists idx_incidents_department_id on incidents(department_id);
create index if not exists idx_incidents_reported_by on incidents(reported_by);
create index if not exists idx_incidents_status on incidents(status);
create index if not exists idx_corrective_actions_incident_id on corrective_actions(incident_id);
create index if not exists idx_registration_requests_status on registration_requests(request_status);
create index if not exists idx_audit_logs_created_at on audit_logs(created_at desc);
